import { error } from '@sveltejs/kit';
import type { RequestEvent } from "./$types";
import * as EmailValidator from 'email-validator';
import { env } from '$env/dynamic/private';
import { GoogleSpreadsheet } from "google-spreadsheet";

const SHEET_ID = "1ANWHf_xTo6Fjv9LgMGJ48MqUS0xnj6PwYmE16zwW3ts"

export async function POST({url}: RequestEvent): Promise<Response> {
  console.log("Processing POST request")
  const email = url.searchParams.get("email");
  if (email === null || !EmailValidator.validate(email)) {
    console.error("Email not provided or failed to validate")
    throw error(400, "Please provide a valid email")
  }

  const doc = new GoogleSpreadsheet(SHEET_ID);

  await doc.useServiceAccountAuth({
    // env var values are copied from service account credentials generated by google
    // see "Authentication" section in docs for more info
    client_email: env.SERVICE_ACCT_EMAIL,
    private_key: env.PRIVATE_KEY,
  });

  await doc.loadInfo();

  const sheet = doc.sheetsByIndex[0];
  await sheet.addRow({ email });

  return new Response("Ok");
}